name: Code Analysis

on:
  pull_request:
  workflow_dispatch:

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-dependencies

      - name: Check white-space
        run: yarn pretty

      - name: Build project
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
