name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ./yarn.lock
          registry-url: https://npm.pkg.github.com
          scope: "@arke-systems"

      - name: Install dependencies
        run: yarn install --immutable

        # Based on https://github.com/actions/setup-node/issues/942
      - name: Authentication
        run: 'echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: yarn build

      - name: Publish CLI package
        run: yarn npm publish --tolerate-republish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
