name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ./yarn.lock
          registry-url: https://registry.npmjs.org
          scope: "@arke-systems"

      - name: Install dependencies
        run: yarn install --immutable

        # Based on https://github.com/actions/setup-node/issues/942
      - name: Authentication
        run: 'echo npmAuthToken: "$NPM_AUTH_TOKEN" >> ./.yarnrc.yml'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES_NPM }}

      - name: Build project
        run: yarn build

      - name: Publish CLI package
        run: yarn npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES_NPM }}
