name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-dependencies

      - name: Publish package to NPM
        shell: bash
        run: yarn npm publish --access public
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org
          YARN_NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES_NPM }}

      - name: Publish package to GitHub
        shell: bash
        run: yarn npm publish
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
